### ISSUE TITLE
jdk.internal.jrtfs conflict

### ISSUE THREAD

**Issue by noraj** [mindolph/Mindolph#2]
I have this issue with [OpenJDK](https://openjdk.java.net/) / [OpenJFX](https://wiki.openjdk.java.net/display/OpenJFX/Main) version 19 and 17.

```
Error occurred during initialization of boot layer
java.lang.LayerInstantiationException: Package jdk.internal.jrtfs in both module jrt.fs and module java.base
```

![image](https://user-images.githubusercontent.com/16578570/220314234-b117d708-4ca9-4f76-8b35-b7ee9fa97ebb.png)

**Comment by mindolph** [comment]
The  --module-path  should be your JavaFX SDK path instead of OpenJDK lib path.

**Comment by noraj** [comment]
Maybe [Mindolph](https://github.com/mindolph/Mindolph) works only with Oracle JDX and JavaFX (Oracle JDK commercially licensed build of OpenJFX) and not witj OpenJDK / OpenJFX?

**Comment by mindolph** [comment]
I see, I have tried OpenJDK 19 with JavaFX 17 on macOS but it was OK, let me try it on Linux once I have chance. BTW, which Linux distribution are you using?

**Comment by noraj** [comment]
I'm using ArchLinux. I see in various places that OpenJFX home is commonly `${JAVA_HOME}/lib/`.

**Comment by noraj** [comment]
I copied the OpenJFX files in a temporary directory and it works.

```
$ tmpfolder=$(mktemp -d)
$ cp $(pacman -Ql java-openjfx | grep -E /usr/lib/jvm/java-19-openjdk/lib/.+ | cut -f 2 -d ' ') $tmpfolder
$ java --module-path $tmpfolder --add-modules java.sql,javafx.controls,javafx.fxml,javafx.swing,javafx.web -jar /tmp/Mindolph-1.0.jar
```

So the issue is that the OpenJDK libraries and OpenJFX ones are in the same folder.

But why do I even have to specify the path and modules for Mindolph? For example [AsciidocFX](https://www.asciidocfx.com/) that also relies on JavaFX/OpenJFX I don't need to provide the JFX path.

```
$ wget https://github.com/asciidocfx/AsciidocFX/releases/download/v1.8.4/AsciidocFX_Linux.tar.gz
$ tar xaf AsciidocFX_Linux.tar.gz 
$ ./AsciidocFX/AsciidocFX
```

**Comment by mindolph** [comment]
The reason why AsciidocFX doesn't need --module-path is it is bundled with JFX libraries for Linux, so you can launch the jar without providing JFX path. Actually I can run Mindolph-1.0.jar without that path on my macOS because it was built with libraries for macOS, maybe I would release the jar file with Linux JFX libraries in next version.

For Recaf, I did some research but I don't know why it doesn't need any JFX path specified on any platform, I guess it is because  of the java 8 libraries but I'm not sure about it.
